services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.7.1
    entrypoint: ["anvil"]
    command:
      - --host=0.0.0.0
      - --port=8545
      - --chain-id=31337
      - --hardfork=cancun
      - --timestamp=1700000000
      - --order=fifo
    ports:
      - "127.0.0.1::8545"
